source 'https://github.com/CocoaPods/Specs.git'

target 'SPBase_Example', :exclusive => true do
  pod 'SPBase', :path => '../'
end

target 'SPBase_Tests', :exclusive => true do
  pod 'SPBase', :path => '../'
end
