source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SPBase_Example', :exclusive => true do
  pod 'SPBase', :path => '../'
end

target 'SPBase_Tests', :exclusive => true do
  pod 'SPBase', :path => '../'

  pod 'FBSnapshotTestCase'
end
